---
- name : Enable http and https services
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https

- name: Configure firewall rules on the ports
  firewalld:
    port: 5050/tcp
    permanent: true
    state: enabled
  

- name: Configure firewall rules on the ports
  firewalld:
    port: 5051/tcp
    permanent: true
    state: enabled

- name: Configure firewall rules on the ports
  firewalld:
    port: 2181/tcp
    permanent: true
    state: enabled

- name: Configure firewall rules on the ports
  firewalld:
    port: 2888/tcp
    permanent: true
    state: enabled

- name: Configure firewall rules on the ports
  firewalld:
    port: 3888/tcp
    permanent: true
    state: enabled
    
- name: Reload firewall
  shell: firewall-cmd --reload
  
- name: Add mesosphere repository
  yum:
    name: http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    state: present

- name: Install Mesos and ZooKeeper
  yum:
    name: ['mesos', 'mesosphere-zookeeper']
    state: present
    update_cache: yes

- name: Start mesos-master service 
  systemd:
    name: mesos-master
    state: started
    enabled: yes

- name: "Set up ID {{ master_id }} on /var/lib/zookeeper/myid"
  copy:
    dest: "/var/lib/zookeeper/myid"
    content: |
      {{ master_id }}

- name : Set up zoo.cfg
  copy: 
    src: "{{ role_path }}/files/zoo.cfg"
    dest: "{{ zookeeper_path }}/conf/zoo.cfg"
  
- name: set up /etc/mesos/zk
  copy: 
    src: "{{ role_path }}/files/zk"
    dest: /etc/mesos/zk
  
- name: Remove quorum file
  file:
    path: /etc/mesos-master/quorum 
    state: absent

- name: Set up ID new quorum file
  copy:
    dest: "/etc/mesos-master/quorum"
    content: |
      2

- name: Set up cluster file
  copy:
    dest: "/etc/mesos-master/cluster"
    content: |
      canaima

- name: Set up hostname file
  copy:
    dest: "/etc/mesos-master/hostname"
    content: |
      {{ master_hostname }}

- name: Set up ip file
  copy:
    dest: "/etc/mesos-master/ip"
    content: |
      {{ master_ip }}

- name: Restart mesos service 
  systemd:
    name: mesos-master
    state: restarted

- name: Restart zookeeper service 
  systemd:
    name: zookeeper
    state: restarted

- name: Disable mesos-slave service 
  systemd:
    name: mesos-slave
    state: stopped
    enabled: no

- name: Init master nodes leader
  systemd:
    name: mesos-master 
    state: stopped
  when: leader == "true"

- name: Init master nodes leader
  command: /bin/mesos master --work_dir=/tmp/mesos --ip=192.168.4.169 --hostname_lookup=false &
  when: leader == "true"