---
- name : Enable http and https services
  firewalld:
    service: "{{ item }}"
  permanent: true
  with_items:
    - http
    - https

- name: Add mesosphere repository
  yum_repository:
    name: mesosphere-el-repo-7-1
    description: mesosphere repo
    baseurl: http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm

- name: Install Mesos and ZooKeeper
  yum:
    name: ['mesos', 'mesosphere-zookeeper']
    state: present
    update_cache: yes

- name: Start mesos-master service 
  systemd:
    name: mesos-master
    state: started
    enabled: yes

- name: "Set up ID {{ master_id }} on /var/lib/zookeeper/myid"
  copy:
    dest: "/var/lib/zookeeper/myid"
    content: |
      "{{ master_id }}"

- name : Set up zoo.cfg
  copy: 
    src: "{{ role_path }}/files/zoo.cfg"
    dest: "{{ zookeeper_path }}/conf/zoo.cfg"

- name: Update zk
  lineinefile: 
    path: /etc/mesos/zk
    line: 'zk://192.168.56.20:2181,192.168.56.21:2181,192.168.56.22:2181/mesos'

- name: Remove quorum file
  file:
    path: /etc/mesos-master/quorum 
    state: absent

- name: Set up ID new quorum file
  copy:
    dest: "/etc/mesos-master/quorum"
    content: |
      2

- name: Set up cluster file
  copy:
    dest: "/etc/mesos-master/cluster"
      content: |
        canaima

- name: Set up hostname file
  copy:
    dest: "/etc/mesos-master/hostname"
      content: |
        "{{ master_hostname }}"

- name: Set up ip file
  copy:
    dest: "/etc/mesos-master/hostname"
      content: |
        "{{ master_ip }}"

- name: Restart mesos service 
  systemd:
    name: mesos-master
    state: restarted

- name: Restart zookeeper service 
  systemd:
    name: zookeeper
    state: restarted

- name: Disable mesos-slave service 
  systemd:
    name: zookeeper
    state: stopped
    enabled: no