---
- name : Enable http and https services
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https

- name: Configure firewall rules on the ports
  firewalld:
    port: 5050/tcp
    permanent: true
    state: enabled
  

- name: Configure firewall rules on the ports
  firewalld:
    port: 5051/tcp
    permanent: true
    state: enabled

- name: Configure firewall rules on the ports
  firewalld:
    port: 2181/tcp
    permanent: true
    state: enabled

- name: Configure firewall rules on the ports
  firewalld:
    port: 2888/tcp
    permanent: true
    state: enabled

- name: Configure firewall rules on the ports
  firewalld:
    port: 3888/tcp
    permanent: true
    state: enabled
    
- name: Reload firewall
  shell: firewall-cmd --reload
  
- name: Add mesosphere repository
  yum:
    name: http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    state: present

- name: Install Mesos and ZooKeeper
  yum:
    name: ['mesos', 'mesosphere-zookeeper']
    state: present
    update_cache: yes

- name: Start mesos-slave service 
  systemd:
    name: mesos-slave
    state: started
    enabled: yes

- name: Update zk
  lineinfile: 
    path: /etc/mesos/zk
    line: 'zk://192.168.56.20:2181,192.168.56.21:2181,192.168.56.22:2181/mesos'
  
- name: Set up hostname file
  copy:
    dest: "/etc/mesos-slave/hostname"
    content: |
      {{ slave_hostname }}

- name: Set up ip file
  copy:
    dest: "/etc/mesos-slave/hostname"
    content: |
      {{ slave_ip }}

- name: Disable mesos-master service 
  systemd:
    name: mesos-master
    state: stopped
    enabled: no

- name: Disable zookeeper service 
  systemd:
    name: zookeeper
    state: stopped
    enabled: no

- name: Restart mesos-slave service 
  systemd:
    name: mesos-slave
    state: restarted
    enabled: yes
